[IBM Quantum Learning](https://learning.quantum.ibm.com/)\
[Basics of quantum information](https://learning.quantum.ibm.com/course/basics-of-quantum-information)\
[Multiple systems](https://learning.quantum.ibm.com/course/basics-of-quantum-information/multiple-systems)

In [1]:
import numpy as np

In [9]:
vec1 = np.array([[1],
				 [3],
				 [5]])

vec2 = np.array([[6],
				 [4],
				 [2]])

print(np.tensordot(vec1, vec2, 0))

[[[[ 6]
   [ 4]
   [ 2]]]


 [[[18]
   [12]
   [ 6]]]


 [[[30]
   [20]
   [10]]]]
