[IBM Quantum Learning](https://learning.quantum.ibm.com/)\
[Basics of quantum information](https://learning.quantum.ibm.com/course/basics-of-quantum-information)\
[Multiple systems](https://learning.quantum.ibm.com/course/basics-of-quantum-information/multiple-systems)

In [13]:
import numpy as np

# Set precision to all np matrix
np.set_printoptions(precision=2)

A simple, yet critically important, idea to keep in mind going into this lesson is that we can always choose to view multiple systems together as if they form a single, compound system — to which the discussion in the previous lesson applies.

# Classical information

### Classical states via the Cartesian product

In simple terms, the Cartesian product is precisely the mathematical notion that captures the idea of viewing an element of one set and an element of a second set together, as if they form a single element of a single set.

$$\Sigma_{1} \times \cdots \times \Sigma_{n} = \{(a_{1}, \ldots, a_{n}) : a_{1} \in \Sigma_{1}, \ldots, a_{n} \in \Sigma_{n}\}$$


### Representing states as strings

(The set $\{0, 1\}$ is commonly referred to as the binary alphabet.) There are then $2^{10} = 1024$ classical states of the joint system $(\Phi_1, \ldots, \Phi_{10})$, which are the elements of the set


$$\Sigma_{1} \times \Sigma_{2} \times \cdots \times \Sigma_{10} = \{0, 1\}^{10}$$

Written as strings, these classical states look like this:

0000000000  
0000000001  
0000000010  
0000000011  
0000000100  
$\vdots$  
1111111111


For the classical state 0001010000, for instance, we see that $X_4$ and $X_6$ are in the state 1, while all other systems are in the state 0.


### Probabilistic state


\begin{align*}
\text{Pr}((X,Y) = (0,0)) &= \frac{1}{2} \\
\text{Pr}((X,Y) = (0,1)) &= 0 \\
\text{Pr}((X,Y) = (1,0)) &= 0 \\
\text{Pr}((X,Y) = (1,1)) &= \frac{1}{2}
\end{align*}


### Ordering Cartesian product state sets

For example, according to this convention, the Cartesian product $\{1,2,3\} \times \{0,1\}$ is ordered like this:

(1, 0), (1, 1), (2, 0), (2, 1), (3, 0), (3, 1).








### Independence of two systems

In [14]:
vec_00 = (1/6) * np.array([[1],
				   		   [0],
				   		   [0],
				   		   [0]])

vec_01 = (1/12) * np.array([[0],
				   			[1],
				   			[0],
				   			[0]])

vec_10 = (1/2) * np.array([[0],
				  		   [0],
				  		   [1],
				  		   [0]])

vec_11 = (1/4) * np.array([[0],
				   		   [0],
				   		   [0],
				   		   [1]])

cat_fi = (1/4) * np.array([[1],
				   		   [0]]) + (3/4) * np.array([[0],
									   				 [1]])

cat_psi = (2/3) * np.array([[1],
				   		    [0]]) + (1/3) * np.array([[0],
									   				  [1]])

print(vec_00 + vec_01 + vec_10 + vec_11)
print("\n")
print(np.tensordot(cat_fi, cat_psi, 0))

[[0.17]
 [0.08]
 [0.5 ]
 [0.25]]


[[[[0.17]
   [0.08]]]


 [[[0.5 ]
   [0.25]]]]


Having defined independence between two systems, we can now define correlation precisely as a lack of independence.

In [15]:
vec_00 = (1/2) * np.array([[1],
				   		   [0],
				   		   [0],
				   		   [0]])

vec_01 = (0) * np.array([[0],
				   		 [1],
				   		 [0],
				   		 [0]])

vec_10 = (0) * np.array([[0],
				  		 [0],
				  		 [1],
				  		 [0]])

vec_11 = (1/2) * np.array([[0],
				   		   [0],
				   		   [0],
				   		   [1]])

print(vec_00 + vec_01 + vec_10 + vec_11)

[[0.5]
 [0. ]
 [0. ]
 [0.5]]


### Tensor products of vectors

``` python
​(α₁ ⋮ αₘ) ⊗ (β₁ ⋮ βₖ) = 
    (α₁β₁ ⋮ α₁βₖ) 
    (α₂β₁ ⋮ α₂βₖ) 
          ⋮
    (αₘβ₁ ⋮ αₘβₖ)


In [16]:
vec1 = np.array([[1],
				 [3],
				 [5]])

vec2 = np.array([[6],
				 [0],
				 [2]])

print(np.tensordot(vec1, vec2, 0))

[[[[ 6]
   [ 0]
   [ 2]]]


 [[[18]
   [ 0]
   [ 6]]]


 [[[30]
   [ 0]
   [10]]]]


1. Linearity in the first argument:

(|ϕ₁⟩ + |ϕ₂⟩) ⊗ |ψ⟩ = |ϕ₁⟩ ⊗ |ψ⟩ + |ϕ₂⟩ ⊗ |ψ⟩


In [17]:
cat_fi_1 = np.array([[1/2],
				      [1/2]])

cat_fi_2 = np.array([[1/4],
				      [3/4]])

cat_psi = np.array([[3/5],
				    [2/5]])

res_1 = np.tensordot((cat_fi_1 + cat_fi_2), cat_psi, 0)
res_2 = np.tensordot(cat_fi_1 , cat_psi, 0) + np.tensordot(cat_fi_2 , cat_psi, 0)
print(f"{res_1}\n\n{res_2}")



[[[[0.45]
   [0.3 ]]]


 [[[0.75]
   [0.5 ]]]]

[[[[0.45]
   [0.3 ]]]


 [[[0.75]
   [0.5 ]]]]


(α|ϕ⟩) ⊗ |ψ⟩ = α(|ϕ⟩ ⊗ |ψ⟩)

In [18]:
alpha = 2

cat_fi = np.array([[1/4],
				   [3/4]])

cat_psi = np.array([[3/5],
				    [2/5]])

res_1 = np.tensordot((alpha * cat_fi), cat_psi, 0)
res_2 = alpha * np.tensordot(cat_fi , cat_psi, 0)
print(f"{res_1}\n\n{res_2}")

[[[[0.3]
   [0.2]]]


 [[[0.9]
   [0.6]]]]

[[[[0.3]
   [0.2]]]


 [[[0.9]
   [0.6]]]]


2. Linearity in the second argument:

|ϕ⟩ ⊗ (|ψ₁⟩ + |ψ₂⟩) = |ϕ⟩ ⊗ |ψ₁⟩ + |ϕ⟩ ⊗ |ψ₂⟩

In [19]:
cat_fi = np.array([[3/5],
				    [2/5]])

cat_psi_1 = np.array([[1/2],
				      [1/2]])

cat_psi_2 = np.array([[1/4],
				      [3/4]])


res_1 = np.tensordot(cat_fi, (cat_psi_1 + cat_psi_2), 0)
res_2 = np.tensordot(cat_fi , cat_psi_1, 0) + np.tensordot(cat_fi , cat_psi_2, 0)
print(f"{res_1}\n\n{res_2}")

[[[[0.45]
   [0.75]]]


 [[[0.3 ]
   [0.5 ]]]]

[[[[0.45]
   [0.75]]]


 [[[0.3 ]
   [0.5 ]]]]


|ϕ⟩ ⊗ (α|ψ⟩) = α(|ϕ⟩ ⊗ |ψ⟩)

In [20]:
cat_fi = np.array([[1/4],
				   [3/4]])

alpha = 2

cat_psi = np.array([[3/5],
				    [2/5]])

res_1 = np.tensordot(cat_fi, (alpha * cat_psi), 0)
res_2 = alpha * np.tensordot(cat_fi , cat_psi, 0)
print(f"{res_1}\n\n{res_2}")

[[[[0.3]
   [0.2]]]


 [[[0.9]
   [0.6]]]]

[[[[0.3]
   [0.2]]]


 [[[0.9]
   [0.6]]]]


### Independence and tensor products for three or more systems

$$\left|\psi \right\rangle = \left|\phi_1 \right\rangle \otimes \cdots \otimes \left|\phi_n \right\rangle$$

In [21]:
from itertools import product

# Define the sets of elements
set1 = [0, 1]
set2 = [0, 1]
set3 = [0, 1]

# Calculate the Cartesian product
cartesian_product = list(product(set1, set2, set3))

# Print the Cartesian product
print("Cartesian product:", cartesian_product)


Cartesian product: [(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1)]


In [22]:
cat_a_1 = np.array([[1],
					[0]])

cat_a_2 = np.array([[0],
					[1]])

cat_a_3 = np.array([[1],
					[0]])

print(cartesian_product[2])
print("\n")
print(np.tensordot(np.tensordot(cat_a_1, cat_a_2, 0), cat_a_3, 0))

(0, 1, 0)


[[[[[[0]
     [0]]]


   [[[1]
     [0]]]]]




 [[[[[0]
     [0]]]


   [[[0]
     [0]]]]]]


### Measurements of probabilistic states

### Partial measurements



​






$$\Pr(X=a) = \sum_{b \in \Gamma} \Pr((X,Y)=(a,b)).$$


$$\Pr(Y=b \mid X=a) = \frac{\Pr((X,Y)=(a,b))}{\Pr(X=a)}$$

$$\left|\psi \right\rangle = \sum_{(a,b) \in \Sigma \times \Gamma} p_{ab} \left|ab \right\rangle$$

$$\left| \psi \right\rangle = \frac{2}{1} \left|0,1\right\rangle + \frac{1}{2} \left|0,3\right\rangle + \frac{1}{2} \left|1,1\right\rangle + \frac{1}{6} \left|1,2\right\rangle + \frac{1}{6} \left|1,3\right\rangle.$$


$$ \sum_{a \in \Sigma} \left( \sum_{c \in \Gamma} p_{ac} \right) \left| a \right\rangle.$$

$$\left| \psi \right\rangle = \left|0\right\rangle \otimes \left(\frac{1}{2} \left|1\right\rangle + \frac{1}{12} \left|3\right\rangle\right) + \left|1\right\rangle \otimes \left(\frac{1}{12} \left|1\right\rangle + \frac{1}{6} \left|2\right\rangle + \frac{1}{6} \left|3\right\rangle\right).$$


$$\Pr(X=0) = \frac{1}{2} + \frac{1}{12} = \frac{7}{12}$$

$$\Pr(X=1) = \frac{1}{12} + \frac{1}{6} + \frac{1}{6} = \frac{5}{12}$$

$$\left| \pi_{a} \right\rangle = \frac{\sum_{b \in \Gamma} p_{ab} \left| b \right\rangle}{\sum_{c \in \Gamma} p_{ac}}$$


$$\frac{\frac{1}{2} \left|1\right\rangle + \frac{1}{12} \left|3\right\rangle}{\frac{7}{12}} = \frac{6}{7} \left|1\right\rangle + \frac{1}{7} \left|3\right\rangle$$

$$\frac{\frac{1}{12} \left|1\right\rangle + \frac{1}{6} \left|2\right\rangle + \frac{1}{6} \left|3\right\rangle}{\frac{5}{12}} = \frac{1}{5} \left|1\right\rangle + \frac{2}{5} \left|2\right\rangle + \frac{2}{5} \left|3\right\rangle$$

### Operations on probabilistic states

$$\sum_{k=0}^{7} \left| (k+1) \mod 8 \right\rangle \left\langle k \right|$$


In [50]:
from copy import deepcopy

k = 0
k_max = 7
vec_size = 8

matrix_final = np.zeros((vec_size, vec_size))
vec = np.zeros((1, vec_size))
ket_vec_curr = deepcopy(vec)
bra_vec_curr = deepcopy(ket_vec_curr.reshape(-1, 1))

while k <= k_max:
	ket_vec_curr = deepcopy(vec)
	bra_vec_curr = deepcopy(vec)
	ket_vec_curr = deepcopy(ket_vec_curr.reshape(-1, 1))
	if k + 1 == vec_size:
		ket_vec_curr[0] = 1
	else:
		ket_vec_curr[k+1] = 1
	bra_vec_curr[0][k] = 1
	matrix_curr =  np.dot(ket_vec_curr, bra_vec_curr)
	matrix_final = matrix_final + matrix_curr
	k = k + 1

print(matrix_final)

[[0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]


### Tensor products of matrices

In [41]:
M = np.array([[1],
			  [0]])

N = np.array([[1, 0]])

print(np.dot(M, N))

[[1 0]
 [0 0]]
