In [2]:
import numpy as np
import math

In [4]:
# Representation of the bit in state 0 and 1.
# Building a simple probability vector.

bit_0 = np.array([[1],
				  [0]])

bit_1 = np.array([[0],
			      [1]])

bit_0 = 3/4 * bit_0

bit_1 = 1/4 * bit_1

probability_vector = bit_0 + bit_1
print(probability_vector)

[[0.75]
 [0.25]]


In [19]:
# Applying a deterministic function (matrix) to each bit state. 

# |0>
cat_0 = np.array([[1],
				  [0]])

# |1>
cat_1 = np.array([[0],
				  [1]])

# f1(a) = 0
m_1 = np.array([[1, 1],
		[0, 0]])

# f2 (identity function): f2(a) = a
m_2 = np.array([[1, 0],
		[0, 1]])

# f3 (NOT function): f3(0) = 1 and f3(1) = 0
m_3 = np.array([[0, 1],
		[1, 0]])

# f4(a) = 1
m_4 = np.array([[0, 0],
		[1, 1]])

result_1 = np.dot(m_1, cat_0)
result_2 = np.dot(m_1, cat_1)

result_3 = np.dot(m_2, cat_0)
result_4 = np.dot(m_2, cat_1)

result_5 = np.dot(m_3, cat_0)
result_6 = np.dot(m_3, cat_1)

result_7 = np.dot(m_4, cat_0)
result_8 = np.dot(m_4, cat_1)

print(f"result_1: \n{result_1}\nresult_2: \n{result_2}\n")
print(f"result_3: \n{result_3}\nresult_4: \n{result_4}\n")
print(f"result_5: \n{result_5}\nresult_6: \n{result_6}\n")
print(f"result_7: \n{result_7}\nresult_8: \n{result_8}\n")


result_1: 
[[1]
 [0]]
result_2: 
[[1]
 [0]]

result_3: 
[[1]
 [0]]
result_4: 
[[0]
 [1]]

result_5: 
[[0]
 [1]]
result_6: 
[[1]
 [0]]

result_7: 
[[0]
 [1]]
result_8: 
[[0]
 [1]]



In [21]:
m = np.array([[0, 1, 0],
	         [1, 0, 1]])

a = np.array([[1],
			  [0],
			  [0]])

b = np.array([[1, 0, 0]])
c = np.array([[0],
			  [1]])


print(np.dot(m, a))
print(np.dot(c, b))


[[0]
 [1]]
[[0 0 0]
 [1 0 0]]


In [16]:
# |a><b|; <a||b>

bra_0 = [[1, 0]]

ket_0 = [[1],
		 [0]]

bra_1 = [[0, 1]]

ket_1 = [[0],
		 [1]]

braket_0 = np.dot(bra_0, ket_0)
ket_bra_0 = np.dot(ket_0, bra_0)

braket_1 = np.dot(bra_1, ket_1)
ket_bra_1 = np.dot(ket_1, bra_1)

bra_1ket_0 = np.dot(bra_1, ket_0)
ket_0bra_1 = np.dot(ket_0, bra_1)

print(f"braket_0:\n{braket_0}\n")
print(f"ket_bra_0:\n{ket_bra_0}\n")
print(f"braket_1:\n{braket_1}\n")
print(f"ket_bra_1:\n{ket_bra_1}\n")
print(f"bra_1ket_0:\n{bra_1ket_0}\n")
print(f"ket_0bra_1:\n{ket_0bra_1}\n")

braket_0:
[[1]]

ket_bra_0:
[[1 0]
 [0 0]]

braket_1:
[[1]]

ket_bra_1:
[[0 0]
 [0 1]]

bra_1ket_0:
[[0]]

ket_0bra_1:
[[0 1]
 [0 0]]



In [8]:
# M∣b⟩=(∑∣f(a)⟩⟨a∣)∣b⟩ = ∑∣f(a)⟩⟨a∣b⟩ = ∣f(b)⟩

# ∑ = {1, 2, 3}

# ∣a⟩1
cat_a1 = np.array([[1],
				   [0],
				   [0]])

# ⟨a∣1
bra_a1 = np.array([[1, 0, 0]])

# ∣a⟩2
cat_a2 = np.array([[0],
				   [1],
				   [0]])

cat_b = cat_a2 # Arbitrary choice

# ⟨a∣2
bra_a2 = np.array([[0, 1, 0]])

# ∣a⟩3
cat_a3 = np.array([[0],
				   [0],
				   [1]])

# ⟨a∣3
bra_a3 = np.array([[0, 0, 1]])

# M
M = np.array([[0, 1, 0],
			  [1, 0, 1]])

# M∣a⟩=∣f(a)⟩
print(f"{np.dot(M, cat_a1)}\n")

# M = ∑∣f(a)⟩⟨a∣
M = np.dot(np.dot(M, cat_a1), bra_a1) + \
	np.dot(np.dot(M, cat_a2), bra_a2) + \
	np.dot(np.dot(M, cat_a3), bra_a3)
print(f"{M}\n")

# ∣f(b)⟩ = ∑∣f(a)⟩⟨a∣b⟩

fb = np.dot(np.dot(M, cat_a1), np.dot(bra_a1, cat_b)) + \
	 np.dot(np.dot(M, cat_a2), np.dot(bra_a2, cat_b)) + \
	 np.dot(np.dot(M, cat_a3), np.dot(bra_a3, cat_b))
print(f"{fb}\n")

# M∣b⟩=(∑∣f(a)⟩⟨a∣)∣b⟩
Mb = np.dot(M, cat_b)
print(f"{Mb}\n")

# M∣b⟩=(∑∣f(a)⟩⟨a∣)∣b⟩ = ∑∣f(a)⟩⟨a∣b⟩ = ∣f(b)⟩

[[0]
 [1]]

[[0 1 0]
 [1 0 1]]

[[1]
 [0]]

[[1]
 [0]]



In [5]:
prob_op = np.array([[1, 1/2],
					[0, 1/2]])

bit_0 = np.array([[1],
				 [0]])

bit_1 = np.array([[0],
				 [1]])

first_op = np.dot(prob_op, bit_0)
second_op = np.dot(prob_op, bit_1)

print(f"{first_op}\n")
print(f"{second_op}\n")

[[1.]
 [0.]]

[[0.5]
 [0.5]]



In [6]:
# Define a vector
vector = np.array([1, 2, 2])

# Calculate the norm of the vector
norm = np.linalg.norm(vector)

print("Vector:", vector)
print("Norm of the vector:", norm)

Vector: [1 2 2]
Norm of the vector: 3.0


In [7]:
bit_0 = np.array([[1],
				 [0]])

bit_1 = np.array([[0],
				 [1]])

q_bit_state = ((1 + 2j) / 3) * bit_0 - (2 / 3) * bit_1

print(q_bit_state)

[[ 0.33333333+0.66666667j]
 [-0.66666667+0.j        ]]


In [8]:
# Define your vector as a NumPy array
vector = np.array([[(1+2j)/3], 
				   [-2/3]])

# Calculate the conjugate-transpose
conjugate = np.conjugate(vector)
conjugate_transpose = conjugate.T

np.set_printoptions(precision=2)
print(f"{vector}\n")
print(f"{conjugate}\n")
print(f"{conjugate_transpose}\n")

[[ 0.33+0.67j]
 [-0.67+0.j  ]]

[[ 0.33-0.67j]
 [-0.67-0.j  ]]

[[ 0.33-0.67j -0.67-0.j  ]]



In [9]:
vec_1 = np.array([[1],
				  [0],
				  [0]])

vec_2 = np.array([[0],
				  [2],
				  [0]])

vec_3 = np.array([[0],
				  [0],
				  [3]])

print(vec_1 + vec_2 + vec_3)

[[1]
 [2]
 [3]]


In [12]:
# Some error I dont know why

list = []
number = 0
for i in range(1, 11, 1):
	number = number + i/math.sqrt(385)

print(number)

2.8030595529069404


In [25]:
ket_0 = np.array([[1],
				  [0]])

ket_1 = np.array([[0],
				  [1]])

bra_0 = np.array([[1, 0]])

bra_1 = np.array([[0, 1]])

print(np.dot(bra_0, ket_0))
print("\n")
print(np.dot(ket_0, bra_0))

[[1]]


[[1 0]
 [0 0]]
