In [2]:
import numpy as np
import math

vector_zero = np.array([[1],
						[0]])

vector_one = np.array([[0],
					   [1]])

vector_zero = 3/4 * vector_zero

vector_one = 1/4 * vector_one

vector_probability = vector_zero + vector_one
print(vector_probability)

[[0.75]
 [0.25]]


In [11]:
cat_0 = np.array([[1],
				  [0]])

cat_1 = np.array([[0],
				  [1]])

m_1 = ([[1, 1],
		[0, 0]])

m_2 = ([[1, 0],
		[0, 1]])

m_3 = ([[0, 1],
		[1, 0]])

m_4 = ([[0, 0],
		[1, 1]])

print(np.dot(m_3, cat_0))
print("\n")
print(np.dot(m_3, cat_1))

[[0]
 [1]]


[[1]
 [0]]


In [4]:
ket_0 = [[1],
		 [0]]

bra_1 = [[1, 0]]

four_four = np.dot(ket_0, bra_1)
one_one = np.dot(bra_1, ket_0)

print(f"{four_four}\n")
print(f"{one_one}\n")

[[1 0]
 [0 0]]

[[1]]



In [5]:
prob_op = np.array([[1, 1/2],
					[0, 1/2]])

bit_0 = np.array([[1],
				 [0]])

bit_1 = np.array([[0],
				 [1]])

first_op = np.dot(prob_op, bit_0)
second_op = np.dot(prob_op, bit_1)

print(f"{first_op}\n")
print(f"{second_op}\n")

[[1.]
 [0.]]

[[0.5]
 [0.5]]



In [6]:
# Define a vector
vector = np.array([1, 2, 2])

# Calculate the norm of the vector
norm = np.linalg.norm(vector)

print("Vector:", vector)
print("Norm of the vector:", norm)

Vector: [1 2 2]
Norm of the vector: 3.0


In [7]:
bit_0 = np.array([[1],
				 [0]])

bit_1 = np.array([[0],
				 [1]])

q_bit_state = ((1 + 2j) / 3) * bit_0 - (2 / 3) * bit_1

print(q_bit_state)

[[ 0.33333333+0.66666667j]
 [-0.66666667+0.j        ]]


In [8]:
# Define your vector as a NumPy array
vector = np.array([[(1+2j)/3], 
				   [-2/3]])

# Calculate the conjugate-transpose
conjugate = np.conjugate(vector)
conjugate_transpose = conjugate.T

np.set_printoptions(precision=2)
print(f"{vector}\n")
print(f"{conjugate}\n")
print(f"{conjugate_transpose}\n")

[[ 0.33+0.67j]
 [-0.67+0.j  ]]

[[ 0.33-0.67j]
 [-0.67-0.j  ]]

[[ 0.33-0.67j -0.67-0.j  ]]



In [9]:
vec_1 = np.array([[1],
				  [0],
				  [0]])

vec_2 = np.array([[0],
				  [2],
				  [0]])

vec_3 = np.array([[0],
				  [0],
				  [3]])

print(vec_1 + vec_2 + vec_3)

[[1]
 [2]
 [3]]


In [12]:
# Some error I dont know why

list = []
number = 0
for i in range(1, 11, 1):
	number = number + i/math.sqrt(385)

print(number)

2.8030595529069404


In [25]:
ket_0 = np.array([[1],
				  [0]])

ket_1 = np.array([[0],
				  [1]])

bra_0 = np.array([[1, 0]])

bra_1 = np.array([[0, 1]])

print(np.dot(bra_0, ket_0))
print("\n")
print(np.dot(ket_0, bra_0))

[[1]]


[[1 0]
 [0 0]]
