Continue at:
https://learning.quantum.ibm.com/course/basics-of-quantum-information/single-systems#probabilistic-operations-and-stochastic-matrices

[IBM Quantum Learning](https://learning.quantum.ibm.com/)\
[Basics of quantum information](https://learning.quantum.ibm.com/course/basics-of-quantum-information)\
[Single systems](https://learning.quantum.ibm.com/course/basics-of-quantum-information/single-systems)


In [2]:
import numpy as np
import math

List of symbols:
⟩
⟨
∈
Σ 

# Classical information

### Classical states and probability vectors

Give a system that stores information. This system can be in **one** of a finite number of *classical states* at each instant — a configuration that can be recognized and discribed unambiguously.

Starting point: Let's define a bit to be a system that has classical states 0 and 1.

<< Generalization >> 
Let us give the name **X** to the system being considered, and let us use the symbol Σ to refer to the set of classical states of **X**. Example: If **X** is a bit, then 
Σ = {0,1}. In words, we'll refer to this set as the *binary alphabet*.

Certainty vs Uncertain
Taking **X** as a carrier of information, it may be sufficient to decribe it as simply being in one of its possible classical states. But often in information processing, our knowledge of **X** is uncertain, we represent our knowledge of the classical state of **X** by assigning probabilities to each classical state, resulting in a *probabilistic state*.

A convinient way to represent a probabilistic state is by a column vector, we will refer to it as **probability vectors**.
(3/4)
(1/4)

We can represent any probabilistic state through a column vector satisfying two properties:
1. All entries of the vector are nonnegative real numbers.
2. The sum of the entries is equal to 1. 

In [8]:
# Representation of the bit in state 0 and 1.
# Building a simple probability vector.

bit_0 = np.array([[1],
				  [0]])

bit_1 = np.array([[0],
			      [1]])

bit_0 = 3/4 * bit_0

bit_1 = 1/4 * bit_1

probability_vector = bit_0 + bit_1
print(probability_vector)

[[0.75]
 [0.25]]


### Measuring probabilistic states

Measure a system when it is in a probabilistic state. By measuring a system, we mean tah we look at the system and unambiguously recognize whatever classical state it is in. Measurement changes our knowledge of the system, and therefore changes the probabilistic state that we associate with that system. If we recognize that **X** is in the classical state *a* ∈ Σ. We denote the vector having a 1 in the entry corresponding to *a* and 0 for all other entries by ∣a⟩, this vector is read as "ket a".
For example, assuming that the system we have in mind is a bit, the standard basis vectors arg given by

∣0⟩	=	(1)		and		∣1⟩	=	(0)
		(0)						(1)

Any column vector is a linear combination over the classical states. By establishing the measrement properties of classical systems, the analogous behavior for quantum information might seem less unusual.

## Classical operations
### Deterministic operations

An operation is deterministic if the result is completely determined by the input without any element of chance or uncertainty. where each classical state a ∈ Σ is transformed into f(a) for some function *f* of the form f:Σ→Σ.
The actions of deterministic operations on probabilistic states can be represented by matrix-vector multipliketion. The matrix *M* that represents a given function f:Σ→Σ is one that satisfies 


M∣a⟩ = ∣f(a)⟩

for every a ∈ Σ. Such a matrix always exists and is unique.
Matrices that represent deterministic operations always have exactly one 1 in each column, and 0 for all other entries.

In [2]:
# Applying a deterministic function (matrix) to each bit state. 

# |0>
ket_0 = np.array([[1],
				  [0]])

# |1>
ket_1 = np.array([[0],
				  [1]])

# f1(a) = 0
m_1 = np.array([[1, 1],
				[0, 0]])

# f2 (identity function): f2(a) = a
m_2 = np.array([[1, 0],
				[0, 1]])

# f3 (NOT function): f3(0) = 1 and f3(1) = 0
m_3 = np.array([[0, 1],
				[1, 0]])

# f4(a) = 1
m_4 = np.array([[0, 0],
				[1, 1]])

result_1 = np.dot(m_1, ket_0)
result_2 = np.dot(m_1, ket_1)

result_3 = np.dot(m_2, ket_0)
result_4 = np.dot(m_2, ket_1)

result_5 = np.dot(m_3, ket_0)
result_6 = np.dot(m_3, ket_1)

result_7 = np.dot(m_4, ket_0)
result_8 = np.dot(m_4, ket_1)

print(f"result_1: \n{result_1}\nresult_2: \n{result_2}\n")
print(f"result_3: \n{result_3}\nresult_4: \n{result_4}\n")
print(f"result_5: \n{result_5}\nresult_6: \n{result_6}\n")
print(f"result_7: \n{result_7}\nresult_8: \n{result_8}\n")


result_1: 
[[1]
 [0]]
result_2: 
[[1]
 [0]]

result_3: 
[[1]
 [0]]
result_4: 
[[0]
 [1]]

result_5: 
[[0]
 [1]]
result_6: 
[[1]
 [0]]

result_7: 
[[0]
 [1]]
result_8: 
[[0]
 [1]]



We denote by ⟨a∣ the *row* vector having a 1 in the entry corresponding to *a* and zero for all other entries, for each *a* ∈ Σ. This vector is read as "bra *a*".

In [5]:
# For example, if Σ = {0, 1}, then
bra_0 = np.array([[1, 0]])
bra_1 = np.array([[0, 1]])
print(f"⟨0| = {bra_0} and ⟨1| = {bra_1}\n")

# Matrix multiplication of |0⟩⟨1|
ket_0 = np.array([[1],
				  [0]])
ket_0xbra_1 = np.dot(ket_0, bra_1)
print(f"|0⟩⟨1| = \n{ket_0xbra_1}.\n")

⟨0| = [[1 0]] and ⟨1| = [[0 1]]

|0⟩⟨1| = 
[[0 1]
 [0 0]].



We may express the matrix *M* corresponding to the function *f* as

$ M = \sum_{a ∈ Σ}|f(a)\rangle\langle a| $



In [4]:
# Find the NOT function matrix M3
# f3(0) = 1 and f3(1) = 0
f3_bra_0 = np.array([[1],
					 [0]])
f3_bra_1 = np.array([[0],
					 [1]])
bra_0 = np.array([[1, 0]])
bra_1 = np.array([[0, 1]])
m3 = np.dot(f3_bra_0, bra_0) + np.dot(f3_bra_1, bra_1)
print(f"M3 = \n{m3}.\n")

M3 = 
[[1 0]
 [0 1]].



In [10]:
# |a><b|; <a|b>

bra_0 = [[1, 0]]

ket_0 = [[1],
		 [0]]

bra_1 = [[0, 1]]

ket_1 = [[0],
		 [1]]

braket_0 = np.dot(bra_0, ket_0)
ket_bra_0 = np.dot(ket_0, bra_0)

braket_1 = np.dot(bra_1, ket_1)
ket_bra_1 = np.dot(ket_1, bra_1)

bra_1ket_0 = np.dot(bra_1, ket_0)
ket_0bra_1 = np.dot(ket_0, bra_1)

print(f"braket_0:\n{braket_0}\n")
print(f"ket_bra_0:\n{ket_bra_0}\n")
print(f"braket_1:\n{braket_1}\n")
print(f"ket_bra_1:\n{ket_bra_1}\n")
print(f"bra_1ket_0:\n{bra_1ket_0}\n")
print(f"ket_0bra_1:\n{ket_0bra_1}\n")

braket_0:
[[1]]

ket_bra_0:
[[1 0]
 [0 0]]

braket_1:
[[1]]

ket_bra_1:
[[0 0]
 [0 1]]

bra_1ket_0:
[[0]]

ket_0bra_1:
[[0 1]
 [0 0]]



Operating this sense unity:

M∣b⟩=(∑∣f(a)⟩⟨a∣)∣b⟩ = ∑∣f(a)⟩⟨a∣b⟩ = ∣f(b)⟩

In [11]:
# M∣b⟩=(∑∣f(a)⟩⟨a∣)∣b⟩ = ∑∣f(a)⟩⟨a∣b⟩ = ∣f(b)⟩

# ∑ = {1, 2, 3}

# ∣a⟩1
cat_a1 = np.array([[1],
				   [0],
				   [0]])

# ⟨a∣1
bra_a1 = np.array([[1, 0, 0]])

# ∣a⟩2
cat_a2 = np.array([[0],
				   [1],
				   [0]])

cat_b = cat_a2 # Arbitrary choice

# ⟨a∣2
bra_a2 = np.array([[0, 1, 0]])

# ∣a⟩3
cat_a3 = np.array([[0],
				   [0],
				   [1]])

# ⟨a∣3
bra_a3 = np.array([[0, 0, 1]])

# M
M = np.array([[0, 1, 0],
			  [1, 0, 1]])

# M∣a⟩=∣f(a)⟩
print(f"{np.dot(M, cat_a1)}\n")

# M = ∑∣f(a)⟩⟨a∣
M = np.dot(np.dot(M, cat_a1), bra_a1) + \
	np.dot(np.dot(M, cat_a2), bra_a2) + \
	np.dot(np.dot(M, cat_a3), bra_a3)
print(f"{M}\n")

# ∣f(b)⟩ = ∑∣f(a)⟩⟨a∣b⟩
fb = np.dot(np.dot(M, cat_a1), np.dot(bra_a1, cat_b)) + \
	 np.dot(np.dot(M, cat_a2), np.dot(bra_a2, cat_b)) + \
	 np.dot(np.dot(M, cat_a3), np.dot(bra_a3, cat_b))
print(f"{fb}\n")

# M∣b⟩=(∑∣f(a)⟩⟨a∣)∣b⟩
Mb = np.dot(M, cat_b)
print(f"{Mb}\n")

# M∣b⟩=(∑∣f(a)⟩⟨a∣)∣b⟩ = ∑∣f(a)⟩⟨a∣b⟩ = ∣f(b)⟩

[[0]
 [1]]

[[0 1 0]
 [1 0 1]]

[[1]
 [0]]

[[1]
 [0]]



At this point the names "bra" and "ket" may be evident: putting a "bra" ⟨a| together with a "ket" |b⟩ yields a "bracket" ⟨a|b⟩. This notation and terminology is due to Paul Dirac, and for this reason is known as the "Dirac notation". 


### Probabilistic operations and stochastic matrices

*stochastic* - randomly determined; having a random probability distribution or pattern that may be analyzed statistically but may not be predicted precisely.

Stochastic matrices are matrices satisfying these two properties:

1. All entries are nonnegative real numbers.
2. The entries in every column sum to 1.

Equivalently, stochastic matrices are matrices whose columns all form probability vectors.

In [3]:
# Check if the example matrix does the correct thing by multiplying it with the standard basis vectors.

M_prop = np.array([[1, 1/2],
			       [0, 1/2]])

bit_0 = np.array([[1],
				  [0]])

bit_1 = np.array([[0],
				  [1]])

first_op = np.dot(M_prop, bit_0)
second_op = np.dot(M_prop, bit_1)

print(f"{first_op}\n")
print(f"{second_op}\n")

[[1.]
 [0.]]

[[0.5]
 [0.5]]



With respect to the stochastic matrix description of a probabilistic operation, each column can be viewed as a vector representation of the probalistic state that is generated given whatever classical state input corresponds to that column.

### Compositions of probabilistic operations