[IBM Quantum Learning](https://learning.quantum.ibm.com/)\
[Basics of quantum information](https://learning.quantum.ibm.com/course/basics-of-quantum-information)\
[Single systems](https://learning.quantum.ibm.com/course/basics-of-quantum-information/single-systems)


In [1]:
import numpy as np
import math

## Quantum information

### Quantum state vectors

A quantum state of a system is represented by a column vector, similar to probabilistic states. As before, the indices of the vector label the classical states of the system. Vectors representing quantum states are characterized by these two properties:

1. The entries of a quantum state vector are complex numbers.
2. The sum of the absolute values squared of the entries of a quantum state vector is 1.

Any speedup from a quantum computer, or improvement in a communication protocol, ultimately derives from these simple mathematical changes.

It is quite common to use the notation 
$\left|\psi\right\rangle$, or other names in place of 
$\psi$, to refer to an arbitrary vector that may not necessarily be a standard basis vector.




In [2]:
# Calculating the norm of a vector

# Define a row_vector
row_vector = np.array([[1, 2, 2]])

# Calculate the norm t way to represent of the row_vector
row_norm = np.linalg.norm(row_vector)

# Define a column_vector
column_vector = np.array([[1], 
						  [2], 
						  [2]])

# Calculate the norm of the column_vector
column_norm = np.linalg.norm(column_vector)

print("row_vector:\n", row_vector)
print("Norm of the row_vector:", row_norm)
print("\n")
print("column_vector:\n", column_vector)
print("Norm of the column_vector:", column_norm)

row_vector:
 [[1 2 2]]
Norm of the row_vector: 3.0


column_vector:
 [[1]
 [2]
 [2]]
Norm of the column_vector: 3.0


In [3]:
# Set precision to all np matrix
np.set_printoptions(precision=2)

In [4]:
# Quantum column vector with complex numbers

bit_0 = np.array([[1],
				 [0]])

bit_1 = np.array([[0],
				 [1]])

q_bit_state = ((1 + 2j) / 3) * bit_0 - (2 / 3) * bit_1

print(q_bit_state)
print(np.linalg.norm(q_bit_state))

[[ 0.33+0.67j]
 [-0.67+0.j  ]]
1.0


In [5]:
# Define your vector as a NumPy array
vector = np.array([[(1+2j)/3], 
				   [-2/3]])

# Calculate the conjugate-transpose
conjugate = np.conjugate(vector)
conjugate_transpose = conjugate.T

print(f"{vector}\n")
print(f"{conjugate}\n")
print(f"{conjugate_transpose}\n")

[[ 0.33+0.67j]
 [-0.67+0.j  ]]

[[ 0.33-0.67j]
 [-0.67-0.j  ]]

[[ 0.33-0.67j -0.67-0.j  ]]



In [7]:
# Just summing three vectors

vec_1 = np.array([[1],
				  [0],
				  [0]])

vec_2 = np.array([[0],
				  [2],
				  [0]])

vec_3 = np.array([[0],
				  [0],
				  [3]])

print(vec_1 + vec_2 + vec_3)

[[1]
 [2]
 [3]]


In [ ]:
# (1/385) * Σ(k=0 to 9) (k+1)|k⟩

list = []
number = 0
for i in range(1, 11, 1):
	number = i * (1/math.sqrt(385))
	list.append(number)

vector = np.array(list)
print(np.linalg.norm(vector))

1.0


### Measuring quantum states
Similar to the probabilistic setting, when a system in quantum state is measured, the observer performing the measurement won't see a quantum state vector, but rather some classical state. In this sense, measurements act as the interface between quantum and classical information, through which classical information is extracted from quantum states.
For example, measuring the plus state

$$ 
|+\rangle = \frac{1}{\sqrt{2}}|0\rangle + \frac{1}{\sqrt{2}}|1\rangle
$$

In [ ]:
# Pr(outcome is 0) = |⟨0|+⟩|²
bra_0 = np.array([[1, 0]])
ket_plus = np.array([[1], [1]]) / math.sqrt(2)
print('bra_0:\n', bra_0)
print('ket_plus:\n', ket_plus)
pr_0_sqrt = np.linalg.norm(np.dot(bra_0, ket_plus))
print('pr_0_sqrt:\n', pr_0_sqrt)
pr_0 = pr_0_sqrt ** 2
print('pr_0:\n', pr_0)

print('\n')

# Pr(outcome is 1) = |⟨1|+⟩|²
bra_1 = np.array([[0, 1]])
ket_plus = np.array([[1], [1]]) / math.sqrt(2)
print('bra_1:\n', bra_1)
print('ket_plus:\n', ket_plus)
pr_1_sqrt = np.linalg.norm(np.dot(bra_1, ket_plus))
print('pr_sqrt:\n', pr_1_sqrt)
pr_1 = pr_1_sqrt ** 2
print('pr_1:\n', pr_1)


bra_0:
 [[1 0]]
ket_plus:
 [[0.70710678]
 [0.70710678]]
pr_0_sqrt:
 0.7071067811865475
pr_0:
 0.4999999999999999


bra_1:
 [[0 1]]
ket_plus:
 [[0.70710678]
 [0.70710678]]
pr_sqrt:
 0.7071067811865475
pr_1:
 0.4999999999999999


As a final example, measuring the state

$$

|ψ\rangle = \frac{1+2i}{3}|0\rangle - \frac{2}{3}|1\rangle

$$

has probabilities given by


In [ ]:
# Pr(outcome is 0) = |⟨0|ψ⟩|²
bra_0 = np.array([[1, 0]])
psi = np.array([[1+2j], [-2]]) / 3
print('bra_0:\n', bra_0)
print('psi:\n', psi)
pr_0_sqrt = np.linalg.norm(np.dot(bra_0, psi))
print('pr_0_sqrt:\n', pr_0_sqrt)
pr_0 = pr_0_sqrt ** 2
print('pr_0:\n', pr_0)

print('\n')

# Pr(outcome is 1) = |⟨1|ψ⟩|²
bra_1 = np.array([[0, 1]])
print('bra_1:\n', bra_1)
pr_1_sqrt = np.linalg.norm(np.dot(bra_1, psi))
print('pr_sqrt:\n', pr_1_sqrt)
pr_1 = pr_1_sqrt ** 2
print('pr_1:\n', pr_1)


bra_0:
 [[1 0]]
psi:
 [[ 0.33333333+0.66666667j]
 [-0.66666667+0.j        ]]
pr_0_sqrt:
 0.7453559924999299
pr_0:
 0.5555555555555556


bra_1:
 [[0 1]]
pr_sqrt:
 0.6666666666666666
pr_1:
 0.4444444444444444


### Unitary operations

Similar to the probabilistic setting, operations on quantum states are linear mapping — but rather than being stochastic matrices as in the classical case, operations on quantum state vectors are represented by *unitary matrices*.



$$ UU^\dagger = \mathbb{I} $$

$$ U^\dagger U = \mathbb{I} $$

$ U^\dagger $ is the *conjugate transpose* of $ U $, meaning the matrix obtained by transposing $ U $ and then taking the complex conjugate of each entry.

$$ U^\dagger = \overline{U^T} $$





In [ ]:
# Define your matrix as a NumPy array
matrix = np.array([[1/math.sqrt(2), 1/math.sqrt(2)],
				   [1/math.sqrt(2), -1/math.sqrt(2)]])

# Calculate the conjugate-transpose
conjugate = np.conjugate(matrix)
conjugate_transpose = conjugate.T
inverse = np.linalg.inv(matrix)

print(f"{matrix}\n")
print(f"{conjugate}\n")
print(f"{conjugate_transpose}\n")
print(f"{inverse}\n")

[[ 0.71  0.71]
 [ 0.71 -0.71]]

[[ 0.71  0.71]
 [ 0.71 -0.71]]

[[ 0.71  0.71]
 [ 0.71 -0.71]]

[[ 0.71  0.71]
 [ 0.71 -0.71]]



The condition that $U$ is unitary is equivalent to the condition that multiplication by $U$ does not change the Euclidean norm of any vector. That is, an $n \times n$ matrix $U$ is unitary if and only if $\| U \left| \psi \right\rangle \| = \| \left| \psi \right\rangle \|$ for every $n$-dimensional column vector $\left| \psi \right\rangle$ with complex number entries.


https://learning.quantum.ibm.com/course/basics-of-quantum-information/single-systems#important-examples-of-unitary-operations-on-qubits